### PR TITLE
BSC-86: Checkbox Headless Conversion

### PR DESCRIPTION
**Pull request by brandontrabon**
Got a working version of the headless checkbox finished. Still need to determine how to structure everything correctly.

### CODE REVIEW

**Review by thectogeneral — COMMENTED** [review]
@brandontrabon Instead of using the `../../../../headless/components/component-interfaces.ts` syntax to navigate files, why not use the "@/*" convention. It should make the code less repetitive with the `../../../..` . You can set it in the `tsconfig.json` file.

**Comment by brandontrabon** [comment]
> @brandontrabon Instead of using the `../../../../headless/components/component-interfaces.ts` syntax to navigate files, why not use the "@/*" convention. It should make the code less repetitive with the `../../../..` . You can set it in the `tsconfig.json` file.

That's actually a good idea, especially since these headless components will eventually get moved to their own library.

**Comment by brandontrabon** [comment]
> @brandontrabon Instead of using the `../../../../headless/components/component-interfaces.ts` syntax to navigate files, why not use the "@/*" convention. It should make the code less repetitive with the `../../../..` . You can set it in the `tsconfig.json` file.

OK @thectogeneral I have been looking into this and to make this work I have to define the `baseUrl` property which causes issues in storybook. Since these are eventually going to be moved to their own library I feel leaving the references as is will be OK for the time being. If we find a way to make this work without affecting storybook then we'll implement it at that time. Can you take another look at the code? I would like to get this in, so everyone else can start picking up headless tasks.

**Comment by thectogeneral** [comment]
@brandontrabon I checked through. I didn't find any major issues with the changes you made.  We can work with this.

**Review by thectogeneral — APPROVED** [review]
We can work with this.

**Pull request merged**
